#!/usr/bin/env python3
"""Notebook assembly — generate a reproducible notebook from Plan + artifacts.

Walks the Plan table in .eds/BRIEF.md, finds gate records for each completed
stage, and assembles a notebook with one section per stage.

Usage:
    python assemble_notebook.py \
        --brief-path .eds/BRIEF.md \
        [--out project_notebook.ipynb] \
        [--skip-maturity-check]
"""
import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def create_cell(cell_type: str, source: str | list[str], **kwargs) -> dict:
    """Create a notebook cell."""
    if isinstance(source, str):
        source = source.split("\n")
    # Ensure each line ends with \n except the last
    lines = []
    for i, line in enumerate(source):
        if i < len(source) - 1 and not line.endswith("\n"):
            lines.append(line + "\n")
        else:
            lines.append(line)

    cell = {
        "cell_type": cell_type,
        "metadata": kwargs.get("metadata", {}),
        "source": lines,
    }
    if cell_type == "code":
        cell["execution_count"] = None
        cell["outputs"] = []
    return cell


def parse_plan_table(brief_path: str) -> list[dict]:
    """Parse the Plan table from BRIEF.md."""
    with open(brief_path) as f:
        content = f.read()

    # Find the Plan table (markdown table with stage/status columns)
    stages = []
    in_table = False
    headers = []

    for line in content.split("\n"):
        if "|" in line and ("stage" in line.lower() or "step" in line.lower()):
            headers = [h.strip().lower() for h in line.split("|")[1:-1]]
            in_table = True
            continue
        if in_table and line.strip().startswith("|---") or line.strip().startswith("| ---"):
            continue
        if in_table and "|" in line:
            cells = [c.strip() for c in line.split("|")[1:-1]]
            if len(cells) >= 2:
                stage = {}
                for i, h in enumerate(headers):
                    if i < len(cells):
                        stage[h] = cells[i]
                stages.append(stage)
        elif in_table and not line.strip():
            break

    return stages


def find_gate_record(stage_name: str, eds_root: Path) -> dict | None:
    """Find the most recent gate record for a stage."""
    verification_dir = eds_root / "verification"
    if not verification_dir.exists():
        return None

    # Look for gate records matching this stage
    stage_key = stage_name.lower().replace(" ", "_").replace("-", "_")
    candidates = []
    for f in verification_dir.iterdir():
        if f.suffix == ".json" and stage_key in f.stem.lower():
            candidates.append(f)

    if not candidates:
        return None

    # Return the most recent
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    with open(candidates[0]) as f:
        return json.load(f)


def build_setup_cells(eds_root: Path, contract: dict | None) -> list[dict]:
    """Generate the notebook setup cells."""
    cells = []

    # Header markdown
    cells.append(create_cell("markdown", [
        "# Project Notebook\n",
        "\n",
        f"*Generated by EDS notebook-assembly: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*\n",
        "\n",
        "Each section corresponds to a Plan stage with a verified gate record.\n",
    ]))

    # Setup code cell
    seed = contract.get("seed", 42) if contract else 42
    setup_code = [
        "# --- Setup: reproducibility & imports ---\n",
        f"SEED = {seed}\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        f"np.random.seed(SEED)\n",
        "\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore', category=FutureWarning)\n",
        "\n",
        "# Verify environment\n",
        "import sklearn\n",
        f"print(f'sklearn: {{sklearn.__version__}}, numpy: {{np.__version__}}, pandas: {{pd.__version__}}')\n",
    ]
    cells.append(create_cell("code", setup_code))

    return cells


def build_stage_cells(stage: dict, gate_record: dict | None,
                      eds_root: Path) -> list[dict]:
    """Generate cells for a single Plan stage."""
    cells = []
    stage_name = stage.get("stage", stage.get("step", "Unknown"))
    status = stage.get("status", "unknown")
    gate_ref = stage.get("gate", stage.get("evidence", ""))

    # Stage header
    header_lines = [
        f"## {stage_name}\n",
        "\n",
        f"**Status:** {status}\n",
    ]
    if gate_ref:
        header_lines.append(f"**Gate record:** `{gate_ref}`\n")
    if gate_record:
        checks = gate_record.get("checks", [])
        passed = sum(1 for c in checks if c.get("passed", False))
        header_lines.append(f"**Verification:** {passed}/{len(checks)} checks passed\n")

    cells.append(create_cell("markdown", header_lines))

    # Placeholder code cell for the stage
    code_lines = [
        f"# Stage: {stage_name}\n",
        f"# Status: {status}\n",
        "# TODO: Fill in reproducible code from session artifacts\n",
    ]
    cells.append(create_cell("code", code_lines))

    return cells


def build_results_cells(eds_root: Path) -> list[dict]:
    """Generate summary/results cells at the end."""
    cells = []

    cells.append(create_cell("markdown", [
        "## Results Summary\n",
        "\n",
        "Final metrics, champion model, and operating decisions.\n",
    ]))

    # Load champion if available
    champion_path = eds_root / "models" / "champion.json"
    if champion_path.exists():
        code = [
            "# Champion model summary\n",
            "import json\n",
            f"with open('{champion_path}') as f:\n",
            "    champion = json.load(f)\n",
            "print(json.dumps(champion, indent=2))\n",
        ]
        cells.append(create_cell("code", code))

    # Load bootstrap CI if available
    ci_path = eds_root / "models" / "bootstrap_ci.json"
    if ci_path.exists():
        code = [
            "# Confidence intervals\n",
            f"with open('{ci_path}') as f:\n",
            "    ci = json.load(f)\n",
            "print(f\"Metric: {ci.get('metric', '?')}\")\n",
            "print(f\"Point estimate: {ci.get('point_estimate', '?'):.4f}\")\n",
            "if ci.get('ci_lower'):\n",
            "    print(f\"{ci['ci_level']:.0%} CI: [{ci['ci_lower']:.4f}, {ci['ci_upper']:.4f}]\")\n",
        ]
        cells.append(create_cell("code", code))

    return cells


def create_notebook(cells: list[dict]) -> dict:
    """Create a complete notebook structure."""
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11.0",
            },
        },
        "cells": cells,
    }


def run_maturity_check(notebook_path: str) -> tuple[bool, str]:
    """Run notebook-hygiene maturity_check if available."""
    maturity_script = Path(__file__).parent.parent.parent / "notebook-hygiene" / "scripts" / "maturity_check.py"
    if not maturity_script.exists():
        return True, "maturity_check.py not found — skipping (install notebook-hygiene skill)"

    import subprocess
    result = subprocess.run(
        [sys.executable, str(maturity_script), notebook_path],
        capture_output=True, text=True, timeout=60,
    )
    passed = result.returncode == 0
    output = result.stdout + result.stderr
    return passed, output


def main():
    ap = argparse.ArgumentParser(description="Assemble notebook from Plan + artifacts")
    ap.add_argument("--brief-path", default=".eds/BRIEF.md")
    ap.add_argument("--out", default=None,
                    help="Output notebook path (default: <project>.ipynb)")
    ap.add_argument("--skip-maturity-check", action="store_true")
    args = ap.parse_args()

    if not os.path.exists(args.brief_path):
        print(f"FAILED: Brief not found at {args.brief_path}", file=sys.stderr)
        sys.exit(1)

    eds_root = Path(args.brief_path).parent
    if not eds_root.name == ".eds":
        eds_root = Path(".eds")

    # Parse Plan
    stages = parse_plan_table(args.brief_path)
    if not stages:
        print("WARNING: No Plan table found in Brief. Generating skeleton notebook.")

    # Load contract
    contract_path = eds_root / "models" / "validation_contract.json"
    contract = None
    if contract_path.exists():
        with open(contract_path) as f:
            contract = json.load(f)

    # Build cells
    cells = build_setup_cells(eds_root, contract)

    for stage in stages:
        stage_name = stage.get("stage", stage.get("step", ""))
        gate_record = find_gate_record(stage_name, eds_root)
        cells.extend(build_stage_cells(stage, gate_record, eds_root))

    cells.extend(build_results_cells(eds_root))

    # Create notebook
    notebook = create_notebook(cells)

    # Write output
    out_path = args.out or "assembled_notebook.ipynb"
    with open(out_path, "w") as f:
        json.dump(notebook, f, indent=1)
    print(f"Notebook assembled: {out_path}")
    print(f"  stages: {len(stages)}")
    print(f"  cells: {len(cells)}")

    # Maturity check
    if not args.skip_maturity_check:
        passed, output = run_maturity_check(out_path)
        if passed:
            print(f"  maturity check: PASSED")
        else:
            print(f"  maturity check: FAILED")
            print(output)
            sys.exit(1)
    else:
        print("  maturity check: skipped")


if __name__ == "__main__":
    main()
