#!/usr/bin/env python3
"""Export the FDE feature catalog as a reusable features.py pipeline.

Generates a `build_features(df) -> df` function that reproduces the
complete feature-engineering pipeline. Both notebook and inference.py
import this single source of truth.

Usage:
    python export_features_pipeline.py \
        --catalog-path .eds/features/feature_catalog.json \
        [--out-dir .eds/features/]
"""
import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def load_catalog(catalog_path: str) -> dict:
    """Load the feature catalog."""
    with open(catalog_path) as f:
        return json.load(f)


def generate_feature_spec(catalog: dict) -> dict:
    """Generate the feature_spec.json from the catalog."""
    features = catalog.get("features", [])
    accepted = [f for f in features if f.get("status") == "accepted"]

    spec = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "n_features": len(accepted),
        "feature_names": [f["name"] for f in accepted],
        "dtypes": {f["name"]: f.get("dtype", "float64") for f in accepted},
        "engineered": [
            {
                "name": f["name"],
                "formula": f.get("formula", ""),
                "source_columns": f.get("source_columns", []),
                "hypothesis": f.get("hypothesis", ""),
            }
            for f in accepted
            if f.get("formula")
        ],
        "raw": [f["name"] for f in accepted if not f.get("formula")],
    }
    return spec


def generate_features_py(spec: dict) -> str:
    """Generate the features.py module from the spec."""
    feature_names = spec["feature_names"]
    engineered = spec.get("engineered", [])
    raw = spec.get("raw", [])

    # Build the engineering code blocks
    engineering_blocks = []
    for feat in engineered:
        formula = feat.get("formula", "")
        if formula:
            engineering_blocks.append(
                f"    # {feat['name']}: {feat.get('hypothesis', 'engineered feature')}\n"
                f"    {formula}"
            )

    engineering_section = "\n\n".join(engineering_blocks) if engineering_blocks else "    pass  # No engineered features"

    code = f'''#!/usr/bin/env python3
"""Feature pipeline — single source of truth for feature engineering.

Generated by EDS FDE export: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}

This module is imported by both the notebook and inference.py.
Modifying features? Edit the FDE catalog and re-export — don't edit this file directly.
"""
import numpy as np
import pandas as pd


# Ordered feature list matching model training order
FEATURE_NAMES: list[str] = {json.dumps(feature_names, indent=4)}

# Raw features (used as-is from the source data)
RAW_FEATURES: list[str] = {json.dumps(raw)}


def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """Apply the full feature-engineering pipeline.

    Args:
        df: Raw input DataFrame

    Returns:
        DataFrame with engineered features, columns in FEATURE_NAMES order
    """
    df = df.copy()

    # --- Engineered features ---
{engineering_section}

    # --- Select and order ---
    available = [f for f in FEATURE_NAMES if f in df.columns]
    missing = set(FEATURE_NAMES) - set(df.columns)
    if missing:
        import warnings
        warnings.warn(f"Missing {{len(missing)}} features: {{sorted(missing)[:5]}}")

    return df[available]


def validate_features(df: pd.DataFrame) -> dict:
    """Check that a DataFrame has the expected features with correct dtypes."""
    issues = []
    for feat in FEATURE_NAMES:
        if feat not in df.columns:
            issues.append(f"missing: {{feat}}")

    return {{
        "valid": len(issues) == 0,
        "n_expected": len(FEATURE_NAMES),
        "n_present": sum(1 for f in FEATURE_NAMES if f in df.columns),
        "issues": issues[:10],
    }}
'''
    return code


def main():
    ap = argparse.ArgumentParser(description="Export FDE catalog to features.py pipeline")
    ap.add_argument("--catalog-path", default=".eds/features/feature_catalog.json")
    ap.add_argument("--out-dir", default=".eds/features/")
    args = ap.parse_args()

    if not os.path.exists(args.catalog_path):
        print(f"FAILED: catalog not found at {args.catalog_path}", file=sys.stderr)
        print("Run a feature campaign first (FDE skill) to produce the catalog.")
        sys.exit(1)

    catalog = load_catalog(args.catalog_path)
    spec = generate_feature_spec(catalog)

    os.makedirs(args.out_dir, exist_ok=True)

    # Write feature_spec.json
    spec_path = os.path.join(args.out_dir, "feature_spec.json")
    with open(spec_path, "w") as f:
        json.dump(spec, f, indent=2)
    print(f"feature_spec.json: {spec['n_features']} features ({len(spec.get('engineered', []))} engineered)")

    # Write features.py
    features_code = generate_features_py(spec)
    # Write to project root .eds/features.py for easy import
    features_py_path = os.path.join(args.out_dir, "..", "features.py")
    features_py_path = os.path.normpath(features_py_path)
    with open(features_py_path, "w") as f:
        f.write(features_code)
    print(f"features.py: written to {features_py_path}")

    # Also write a copy in the features dir
    with open(os.path.join(args.out_dir, "features.py"), "w") as f:
        f.write(features_code)

    print(f"\nPipeline exported. Import with:")
    print(f"  from features import build_features, FEATURE_NAMES")


if __name__ == "__main__":
    main()
